server {
    listen 80 default_server;
    server_name _;

    root /var/www/public;
    index index.php;

    client_max_body_size 20M;

    location ~ ^/build/sw\.js$ {
        add_header Service-Worker-Allowed / always;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 120;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
