[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
priority=10

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20
